immobile_data = [
    {
        "id_user": 2,
        "id_status": 1,
        "title": "Casa 2 quartos",
        "description": "Casa com dois quartos. Banheiro e espaço para estacionar",
        "price": '300000.45',
        "n_rooms": 2,
        "square_meters": 60,
        "street": "Rua José Edno",
        "neighborhood": "Morro da Liberdade",
        "city": "Manaus",
        "state": "Amazonas",
        "cep": "69074810",
        "localization": "Rua José Edno 283b. Morro da Liberdade. 69074810"
    },
    {
        "id_user": 2,
        "id_status": 1,
        "title": "Casa 2 quartos",
        "description": "Casa com dois quartos. Banheiro e espaço para estacionar",
        "price": '300000.45',
        "n_rooms": 2,
        "square_meters": 60,
        "street": "Rua José Edno",
        "neighborhood": "Morro da Liberdade",
        "city": "Manaus",
        "state": "Amazonas",
        "cep": "69074810",
        "localization": "Rua José Edno 283b. Morro da Liberdade. 69074810"
    },
    {
        "id_user": 2,
        "id_status": 1,
        "title": "Casa 2 quartos",
        "description": "Casa com dois quartos. Banheiro e espaço para estacionar",
        "price": '300000.45',
        "n_rooms": 2,
        "square_meters": 60,
        "street": "Rua José Edno",
        "neighborhood": "Morro da Liberdade",
        "city": "Manaus",
        "state": "Amazonas",
        "cep": "69074810",
        "localization": "Rua José Edno 283b. Morro da Liberdade. 69074810"
    },
    {
        "id_user": 2,
        "id_status": 1,
        "title": "Casa 2 quartos",
        "description": "Casa com dois quartos. Banheiro e espaço para estacionar",
        "price": '300000.45',
        "n_rooms": 2,
        "square_meters": 60,
        "street": "Rua José Edno",
        "neighborhood": "Morro da Liberdade",
        "city": "Manaus",
        "state": "Amazonas",
        "cep": "69074810",
        "localization": "Rua José Edno 283b. Morro da Liberdade. 69074810"
    },
    {
        "id_user": 2,
        "id_status": 1,
        "title": "Casa 2 quartos",
        "description": "Casa com dois quartos. Banheiro e espaço para estacionar",
        "price": '300000.45',
        "n_rooms": 2,
        "square_meters": 60,
        "street": "Rua José Edno",
        "neighborhood": "Morro da Liberdade",
        "city": "Manaus",
        "state": "Amazonas",
        "cep": "69074810",
        "localization": "Rua José Edno 283b. Morro da Liberdade. 69074810"
    },
    {
        "id_user": 2,
        "id_status": 1,
        "title": "Casa 2 quartos",
        "description": "Casa com dois quartos. Banheiro e espaço para estacionar",
        "price": '300000.45',
        "n_rooms": 2,
        "square_meters": 60,
        "street": "Rua José Edno",
        "neighborhood": "Morro da Liberdade",
        "city": "Manaus",
        "state": "Amazonas",
        "cep": "69074810",
        "localization": "Rua José Edno 283b. Morro da Liberdade. 69074810"
    }
]