immobile_data = [
    {
        "id_user": 2,
        "id_status": 1,
        "title": "Apartamento para alugar com 2 quartos, 56m²",
        "description": "Aparamento COMPLETAMENTE MOBILIADO(Inclusives louças, eletrodomésticos, TV, etc.); Escritório além de 2 quartos; Sol da manhã; Garagem é COBERTA; Há box de garagem para visitantes; Quadra desportiva; Churrasqueira. Vizinho do Tribunal de Contas do Estado, Emporium DB, Farmácia, Igreja e Pizzaria. E próximos a 2 centros comerciais, 3 shopping centers e Universidade Federal do Amazonas.",
        "price": '2640',
        "n_rooms": 2,
        "square_meters": 56,
        "street": "Avenida Ephigênio Salles",
        "neighborhood": "Aleixo",
        "city": "Manaus",
        "state": "Amazonas",
        "cep": "69074810",
        "localization": "Rua José Edno 283b. Morro da Liberdade. 69074810"
    },
    {
        "id_user": 2,
        "id_status": 1,
        "title": "Casa 2 quartos",
        "description": "Disponível - Box, Piscina privativa, Armários nos banheiros, Armários na cozinha, Quartos e corredores com portas amplas, Somente uma casa no terreno, Área de serviço / Indisponível - Banheira de hidromassagem, Varanda, Armários embutidos no quarto, Ar condicionado, Chuveiro a gás, Apartamento cobertura, Fogão incluso, Geladeira inclusa, Banheiro adaptado, Closet, Cozinha americana, Mesas e cadeiras de escritório, Jardim, Quintal",
        "price": '1403',
        "n_rooms": 2,
        "square_meters": 120,
        "street": "Rua Treze de Maio",
        "neighborhood": "Coroado",
        "city": "Manaus",
        "state": "Amazonas",
        "cep": "69074810",
        "localization": "Rua José Edno 283b. Morro da Liberdade. 69074810"
    },
    {
        "id_user": 2,
        "id_status": 1,
        "title": "Casa para alugar com 5 quartos, 450m²",
        "description": "Disponível - Box, Varanda, Armários nos banheiros, Área de serviço / Indisponível - Banheira de hidromassagem, Piscina privativa, Armários embutidos no quarto, Armários na cozinha, Ar condicionado, Chuveiro a gás, Apartamento cobertura, Fogão incluso, Geladeira inclusa",
        "price": '6521',
        "n_rooms": 5,
        "square_meters": 450,
        "street": "Avenida Tancredo Neves",
        "neighborhood": "Parque 10 de Novembro",
        "city": "Manaus",
        "state": "Amazonas",
        "cep": "69074810",
        "localization": "Rua José Edno 283b. Morro da Liberdade. 69074810"
    },
    {
        "id_user": 2,
        "id_status": 1,
        "title": "Casa 2 quartos",
        "description": "Casa com dois quartos. Banheiro e espaço para estacionar",
        "price": '300000.45',
        "n_rooms": 2,
        "square_meters": 60,
        "street": "Rua José Edno",
        "neighborhood": "Morro da Liberdade",
        "city": "Manaus",
        "state": "Amazonas",
        "cep": "69074810",
        "localization": "Rua José Edno 283b. Morro da Liberdade. 69074810"
    },
    {
        "id_user": 2,
        "id_status": 1,
        "title": "Casa 2 quartos",
        "description": "Casa com dois quartos. Banheiro e espaço para estacionar",
        "price": '300000.45',
        "n_rooms": 2,
        "square_meters": 60,
        "street": "Rua José Edno",
        "neighborhood": "Morro da Liberdade",
        "city": "Manaus",
        "state": "Amazonas",
        "cep": "69074810",
        "localization": "Rua José Edno 283b. Morro da Liberdade. 69074810"
    }
]